### ISSUE TITLE
Plugin only works in one window at a time

### ISSUE THREAD

**Issue by mdyan** [Gustaf-C/anki-chinese-support-3#27]
**Describe the bug**
Using Chinese Support in the New Card window and Browse window one after another causes Chinese Support to break in the first window.

**To Reproduce**
1. Open Add Card Window and enable Chinese Support
2. Open Browse window and enable Chinese Support
3. In the browse window, Chinese Support to auto-fill a field
-   To simulate an edit, I delete the Definition field and allow Chinese Support to refill it
4. Go back to Add Card Window and try to use Chinese Support to autofill a new word

**Expected behavior**
Word should auto fill

**Screenshots**
If applicable, add screenshots 
<img width="1048" alt="螢幕擷取畫面 2023-11-05 144016" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/1731593/4ad1159b-b8e1-49ce-837b-c81ee72ece4d">
to help explain your problem.

**Specs (please complete the following information):**
 - OS: Windows 11
 - Anki Version v2.1.66
- Chinese Support Version v0.16.0

**Additional context**
I'm so happy this project finally has a maintainer! 

As far as I know this bug always existed in the Redux as well. I'm not knowledgeable enough about the Anki plugin system to know whether this is even fixable or not. If it seems like it is, I'd be willing to attempt to fix it myself.

**Comment by Gustaf-C** [comment]
I just looked and there is a [pull request](https://github.com/luoliyan/chinese-support-redux/pull/179) for that on the redux version, so if you feel like giving it a shot I would very much appreciate it!

I am quite swamped with other things for the coming weeks, so I won't be able to take a stab at it for quite a while.

**Comment by mdyan** [comment]
@kieranlblack's approach is the right way forward
