### ISSUE TITLE
Incomplete English definition field (for single-word definitions)

### ISSUE THREAD

**Issue by scddo** [Gustaf-C/anki-chinese-support-3#29]
To be clear, this is only for English definitions that are just one word. I have consistently noticed this issue; the definition will be missing the final letter of the word. For example:

秋天: fall (will just say "fal")
盐: salt (will just say "sal")

I am so grateful you decided to keep up the work on this great add-on. Thank you for your time!

**Comment by Gustaf-C** [comment]
I have never had this happen to me, and I can't seem to reproduce it. Are you able to reproduce it consistently?

Also, please follow the bug report template so I have all needed information.

**Comment by kieranlblack** [comment]
I have actually noticed this issue recently too but have not spent the time to look into it.

**Comment by kieranlblack** [comment]
I was just able to reproduce it with minimal effort. We should have here that the last line is "telephone receiver".

<img width="727" alt="image" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/48463323/cdc48dcb-bc3c-4950-9252-1d023a950dcb">

**Comment by kieranlblack** [comment]
Stepped through it with the debugger and identified the issue as being here:

https://github.com/Gustaf-C/anki-chinese-support-3/blob/86d8beac838a60f564125104ed8cdd4172d6aa84/chinese/behavior.py#L84

This is causing definitions which end in `r` or `b` to have those letters stripped off. Check out for example 浴缸

<img width="569" alt="image" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/48463323/02dfb1c2-0896-4ca7-af79-b9f6f51a70ff">

**Comment by scddo** [comment]
@kieranlblack thank you! I realize my description wasn't precisely correct, and I hadn't had the time to change the initial comment.
