### ISSUE TITLE
Automatic fill Hanzi

### ISSUE THREAD

**Issue by Wanessa-Santos3** [Gustaf-C/anki-chinese-support-3#45]
When I attempt to create a card and select "Advanced Chinese" or "Advanced Chinese" and click Hanzi to write my character, it doesn't autofill.

**To Reproduce**
1. Go to "add"
2. Click on chinese advanced and select the card
3. Then click in chinese support button
4. Write the character in the Hanzi space.

**Expected behavior**
It's expected to autofill with the hanzi character, but it 'doesn't.
**What happens to me:**
![Screenshot (76)](https://github.com/Gustaf-C/anki-chinese-support-3/assets/151678173/3557a862-12fb-4733-8c54-5928be278fa4)
**What should happen:**
![Screenshot (78)](https://github.com/Gustaf-C/anki-chinese-support-3/assets/151678173/a395f463-117f-4122-8293-f5ad5b5bd249)

No error message on the screen, just nothing happens.

**Specs 
Windows 10 pro, version 21H1
 - Anki Version [23.10.1] (But i've tried in other versions just like 23.10 and i doesn't work either.
- Chinese Support Version [e.g. v0.17.0] 

 Could you guys please help me. I've uninstalled it, installed other versions, looked for errors in my computer's language, but nothing has worked so far. My keyboard is portuguese (Brazil), does it make any difference?
Obs: I'm sorry about my english grammar, i'm not fluent.

**Comment by kieranlblack** [comment]
Make sure your keyboard layout is set to Chinese. I notice in your screenshot it is not:

<img width="148" alt="image" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/48463323/f1870931-21f1-4a72-b40c-ee6b08da3283">

You can click on this and change it or I think mine is bound to win key + space.

You should see this when you have the correct input selected:

<img width="140" alt="image" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/48463323/78d63706-7028-4fac-9571-3997a6567fab">

**Comment by Wanessa-Santos3** [comment]
It worked, thank you so much. Have a nice day!
