### ISSUE TITLE
Plugin fails to create expected card types after clean installation

### ISSUE THREAD

**Issue by GNeulaender** [Gustaf-C/anki-chinese-support-3#46]
**Describe the bug**
A clean installation of the plugin (no previous version ever installed) doesn't create the template card types "Chinese (Basic)" and "Chinese (Advanced)"

**To Reproduce**
1. Install the plugin using the number 1752008591 in Anki
2. Restart the application.
3. Fail to find the expected card types mentioned.

**Expected behavior**
Have the template card types "Chinese (Basic)" and "Chinese (Advanced)" appear when creating a new note. 

**Screenshots**
List of all my card types after installation:
![image](https://github.com/Gustaf-C/anki-chinese-support-3/assets/5973989/69895ff8-9680-4961-b44e-13fc5f07c0e3)

**Specs (please complete the following information):**
 - OS: Arch Linux
 - Anki Version 23.10.1 (running on flatpak)
- Chinese Support Version 0.17.0

**Additional context**
If someone could share a deck with 1 card of each type so I could manually add the templates, it would be much appreciated.

**Comment by kieranlblack** [comment]
Try clicking on the Add button to the right of the Note Types menu and then adding the Basic and Advanced models.

I agree this is a regression though, seemingly caused by https://github.com/Gustaf-C/anki-chinese-support-3/commit/c8cf8e646cd0b1609013efa9c47d2bdcb196e33a

I won't be able to take a look for a week or so but @Gustaf-C might have time to do so.

**Comment by GNeulaender** [comment]
It work! Thank you!

**Comment by Gustaf-C** [comment]
@kieranlblack I removed the auto creation of the note types since I found it annoying that I could neither remove nor rename the note types without them being automatically created again, so that's a feature.

**Comment by kieranlblack** [comment]
@Gustaf-C this is confusing a lot of people. Perhaps it is best to rethink not automatically adding the note types. I think rather than just removing the auto-adding of them, we should instead aim to make it smarter to avoid the issue you were having with name changes not being detected.

**Comment by tbornon** [comment]
As a new user, I would suggest to at least add the information onto the readme so the users know where to look for instead of taking your time by filling new issues

**Comment by Gustaf-C** [comment]
Yeah it was clearly not as obvious as I thought, I have added it to the readme for now. Hopefully that clears the confusion.
Maybe a better solution would be to add them when the plugin is updated?

**Comment by kieranlblack** [comment]
What if we added a checkbox to the toolbar menu like "ensure note types present" which was checked by default, then if users didn't want them to be automatically added (like yourself) they could uncheck this option, otherwise it would maintain the old behaviour.
