### ISSUE TITLE
Transcription automatically showing on AnkiMobile

### ISSUE THREAD

**Issue by scddo** [Gustaf-C/anki-chinese-support-3#47]
This feature request is related somewhat to a problem. I suppose it is more of a question than a feature request. I am unsure if your add-on is meant to support AnkiMobile. Either way, the feature I would like to see concerns an issue regarding when English definitions are shown first on AnkiMobile. The computer software shows a button that lets you show the transcription of the Pinyin if you need a hint. However, on AnkiMobile, this button is absent, and it just shows the transcription automatically, which is not very helpful if you want to test yourself and see if you remember the pronunciation.

The best solution would be to have AnkiMobile imitate the behavior of the desktop software.

I have attached photos of the issue below:

Anki:

<img width="1040" alt="Screenshot 2023-11-22 at 5 53 48 PM" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/92892316/68f63091-294f-4746-88db-9353ea4b260a">

AnkiMobile:

![IMG_2060](https://github.com/Gustaf-C/anki-chinese-support-3/assets/92892316/b8950a1d-c13a-4da0-8985-bde5b350f91a)

**Comment by Gustaf-C** [comment]
Thanks, I hadn't noticed that.

This is due to the template cards using a custom implementation of hints, if you go into the card layout, change this line on the front template:
`<div class=hint>{{hint_transcription:Pinyin}}</div>`
to this:
`<div class=hint>{{hint:Pinyin}}</div>`
it should work properly. This will be fixed for new note types with 2a22dbd, but that won't fix already created notes.

**Comment by scddo** [comment]
It works like a charm! Thanks so much.

While on the topic of AnkiMobile, do you know the best way or any way to get the KaiTi font to display on iPhone? I have searched for a solution on the internet but to no avail.

**Comment by Gustaf-C** [comment]
Since kaiti isn't available by default on ios you will need to install it as a custom font, there is a guide in [the manual](https://docs.ankimobile.net/custom-fonts.html) that goes through the process.

**Comment by scddo** [comment]
Thank you so much!
