### ISSUE TITLE
Example sentence field

### ISSUE THREAD

**Issue by scddo** [Gustaf-C/anki-chinese-support-3#49]
I would like a field with an example sentence; perhaps it grabs it from a dictionary or MDBG. I know words have multiple meanings and ways to use them, not to mention lots of words are both verbs and nouns, but this would be a cool feature to see in any form.

**Comment by Gustaf-C** [comment]
I fail to see how this would differ from the already exising usage field.

![image](https://github.com/Gustaf-C/anki-chinese-support-3/assets/106698658/e649f069-b890-4f02-b479-51296d2682dd)

**Comment by scddo** [comment]
Does the usage field have to be enabled somehow? From what I can tell, it isn't in the "Chinese (Advanced)" note type.

**Comment by Gustaf-C** [comment]
The note types provided by the addon are just examples, you can add, remove and reorder their fields as you want. Just add a field named "Usage" and it should work. You can find a full list of available fields in the addon config in the addons window.

**Comment by MarkoSchuetz** [comment]
I've created a note type based on the "Chinese (advanced)" note type and added the "Usage" field, but I cannot seem to get that field to be populated. Is there something I have to do to make the add-on query Tatoeba?
