### ISSUE TITLE
Missing Chinese (Basic) and Chinese (Advanced) note type

### ISSUE THREAD

**Issue by Mooderee** [Gustaf-C/anki-chinese-support-3#50]
Description:
After installing the add-on the Chinese (Basic) or Chinese (Advanced) note types are missing. I have tried to create custom type with the field names specified in config.json but the field-filling feature would not work. Re-installing and changing versions of the anki would not fix the issue. 

1. Install anki and Chinese Support
2. Attempt to add new card
3. Select type 
4. See that basic or advanced card note types are missing.

![image](https://github.com/Gustaf-C/anki-chinese-support-3/assets/152077784/a38c6d9b-5e82-47ee-b0ea-ac9d1095899b)

Specs:
 - OS: Windows
 - Anki Version 23.10/23.10.1
- Chinese Support Version v0.17.0

**Comment by kieranlblack** [comment]
See #46.
