### ISSUE TITLE
No type card available

### ISSUE THREAD

**Issue by tbornon** [Gustaf-C/anki-chinese-support-3#51]
Hi,

First of all, thanks for taking the time to upgrade the legacy add on to make it usable onto Anki 23-10

**Describe the bug**
I've just installed the add-on and the basic and advanced type notes are not showing up

**Screenshots**

![image](https://github.com/Gustaf-C/anki-chinese-support-3/assets/35876871/8f504bcd-315f-4102-a61c-fa8adad3b044)

**Specs (please complete the following information):**
 - OS: Windows 11
 - Anki Version 23.10.1 / Python 3.9.15 / Qt 6.6.0
-  Chinese Support Version 0.17.0 

Did I miss something ?

**Comment by kieranlblack** [comment]
See #46.

**Comment by tbornon** [comment]
Oh sorry for the duplicate. Thanks
