### ISSUE TITLE
Auto filling sections when importing data from csv file

### ISSUE THREAD

**Issue by XilaBro** [Gustaf-C/anki-chinese-support-3#53]
**Is your feature request related to a problem? Please describe.**
I'm currently writing out my words on a spreadsheet and then downloading them as a CSV file to import to anki. The problem i've had is that i could get the support to do it one by one but i thought there must be a better way to do it. 

Is there a way to do it that i'm unaware of? specifically auto filling the audio and pinyin.

Thanks

**Comment by Gustaf-C** [comment]
If you have already imported the CSV file to Anki, in the menu bar use Chinese -> Bulk Fill.

**Comment by gretathedog** [comment]
> If you have already imported the CSV file to Anki, in the menu bar use Chinese -> Bulk Fill.

Hello! I selected Chinese and Bulk Fill but then Anki said that I encountered a problem. Not sure exactly where to go from here!

**Comment by Gustaf-C** [comment]
> > If you have already imported the CSV file to Anki, in the menu bar use Chinese -> Bulk Fill.
> 
> Hello! I selected Chinese and Bulk Fill but then Anki said that I encountered a problem. Not sure exactly where to go from here!

I'll need some more information than that to give any meaningful help.

- What anki version?
- What chinese support version? (Help... -> About)
- Can you reproduce the error consistently?
- Are there any crash logs?

**Comment by gretathedog** [comment]
> > Hello! I selected Chinese and Bulk Fill but then Anki said that I encountered a problem. Not sure exactly where to go from here!
> 
> I'll need some more information than that to give any meaningful help.
> 
> * What anki version?
> * What chinese support version? (Help... -> About)
> * Can you reproduce the error consistently?
> * Are there any crash logs?

Hello! Sorry I should have provided more details. It is Version ⁨23.12.1 (1a1d4d54)⁩ and it's the most updated Chinese support 3 version. The error keeps repeating. I'm not sure how to reproduce a crash log but also when attempting to bulk fill, the app has unexpectedly closed. What I haven't tried yet is restarting my computer entirely. I am trying to bulk fill about 10,000 characters because I just discovered anki and am trying to do it with a cvs that I imported from pleco characters.

**Comment by Gustaf-C** [comment]
I suppose you mean that you have the characters as a CSV? In that case could you upload that somewhere, eg pastebin, so I could have a look at it?

I'm quite busy with university finals atm, so if something larger needs fixed it might take a while.
