### ISSUE TITLE
How do i make this addon work for both a sentence field and a word field?

### ISSUE THREAD

**Issue by avc1657** [Gustaf-C/anki-chinese-support-3#70]
In my note type i use both word fields and sentence fields. How do i make the addon work so i add the ruby for the word field and for the sentence field?

All i could figure out is the combination for the Hanzi, Ruby (Pinyin) and the Pinyin field, but what if i wanted a "Word Hanzi", "Word Ruby (Pinyin) and "Word Pinyin"?

**Comment by Gustaf-C** [comment]
I'm afraid I don't quite understand what you're asking for.

Do you have one note type where you want it to autofill two different things?

**Comment by avc1657** [comment]
Exactly. Auto filling word and sentence fields.

**Comment by Gustaf-C** [comment]
The addon only supports autofilling from one field.
