### ISSUE TITLE
Crashes when adding card

### ISSUE THREAD

**Issue by KalObe** [Gustaf-C/anki-chinese-support-3#72]
**Describe the bug**

I just switched from the old version to ACS 3. Thanks so much for providing this!

When adding cards to a deck, the first card I add after starting Anki always works fine. However, when adding the second card and using the auto fill function, the app freezes. The only way to resolve is to force quite the app. When restarting, the first input works fine again, but for the second thing, same thing. 

**To Reproduce**

Add Advanced Card (same issue for basic) to a deck, using auto fill. 
Add a second card. When autofilling the second card, the fields do not fill. Instead, the app freezes (spinning wheel, Mac)

**Expected behavior**
To add a card to my deck

**Specs (please complete the following information):**
 - OS: MacOS Monterey, version 16.6.1
 - Anki Version ⁨23.12.1 
- Chinese Support 3 v0.17.01

**Additional context**

**Comment by Gustaf-C** [comment]
Could you test with the latest Anki beta?

https://github.com/ankitects/anki/releases/tag/24.04beta1

**Comment by Gustaf-C** [comment]
Closing this since the latest anki release should solve this issue.
