### ISSUE TITLE
Adding a note with CTRL + ENTER generates blank note

### ISSUE THREAD

**Issue by arthurnocera** [Gustaf-C/anki-chinese-support-3#74]
When you try to add a note and instead of clicking the ADD button, you use the CTRL + ENTER shortcut it breaks the plugin, generating a blank note

1. Create new note
2. Choose Chinese (Basic)
3. Type any word
4. Press CTRL + ENTER to add note

Expected behavior
Generate a note normally, like when you click the ADD button

Screenshot
https://imgur.com/a/uxS11D0

Specs
 - OS: Windows 10
 - Anki Version v 23.12.1 (1a1d4d54)⁩
- Chinese Support Version v0.17.1

**Comment by Gustaf-C** [comment]
Do you autofill the fields before pressing ctrl+enter?

**Comment by arthurnocera** [comment]
> Do you autofill the fields before pressing ctrl+enter?

No, I wasn't. Now I press TAB to autofill first and then ctrl+enter, this way it works just fine. I wasn't aware of the autofill feature before.
