### ISSUE TITLE
ruby not showing up for advanced cards?

### ISSUE THREAD

**Issue by ghost** [Gustaf-C/anki-chinese-support-3#75]
When I review a Chinese advanced card, how come none of the additional info shows up (ruby, bapomofo), even though when I edit the card it's all there? I'm wondering if there's any way to get the ruby characters to show up specifically when I review, or even replace the colored characters with the ruby version. 

<img width="629" alt="Screenshot 2024-04-04 at 2 21 33 AM" src="https://github.com/Gustaf-C/anki-chinese-support-3/assets/165976789/35305f27-32b3-4a66-b677-755e6a33e56b">

This is what shows up, I guess I mostly want to use ruby because the alignment for the pinyin and characters is really off for the colors

Specs:
 - OS: Mac Sonoma 14.4.1
 - Anki Version 24.04
- Chinese Support Version 3 (latest)

**Comment by Gustaf-C** [comment]
If you want more information to be shown when reviewing you will need to edit the card template.
